# Generated by Django 3.1.7 on 2021-02-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('hire_date', models.DateTimeField(verbose_name='hire-date')),
                ('comm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depy_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.department')),
            ],
        ),
    ]
